### ISSUE TITLE
Is it a cycle?

### ISSUE THREAD

**Issue by nicolaselb** [damienmaguire/Chademo-Fast-Charge-Controller#1]
Hey guys,

Will the vehicle keep sending the parameters via CAN every 100ms during all states or just during RUNNING?

In state SEND_INITIAL_PARAMS there is a _bChademoSendRequests = 1_; saying "**causes chademo frames to be sent out every 100ms**", but still it is not clear to me.

Thanks!

**Comment by nunojsferreira** [comment]
I am not using this code specifically. but I can confirm that the car keeps sending the params through all the cycle.

**Comment by nicolaselb** [comment]
Obrigado!
